### ISSUE TITLE
The file string is missing

### ISSUE THREAD

**Issue by Mardoqueu** [zaingz/quoteit_android#2]

**Comment by ghost** [comment]
I have ignored that file. My Parse.com and facebook app ids were there. Kindly create your own app at parse and facebook and insert those ids in the strings.xml file

**Comment by Mardoqueu** [comment]
I did that, I was just trying help. Kindly thank you ever so much!

**Comment by ghost** [comment]
i appreciate it. thanks

**Comment by vbadvanced** [comment]
It would be better to include that file. Some other resources like activity titles are also there. Maybe you should use a separate xml file for your private data then ignore that file. ;)
